### Get all posts
GET http://localhost:4000/feed/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJpbmFtcmFsYW1zYWxAZ21haWwuY29tIiwiX2lkIjoiNjJhZDRlMDg3NmEwZjE0OWJkNmVkYzE5IiwiaWF0IjoxNjU2MjMwNDEwLCJleHAiOjE2NTg4MjI0MTB9.kbmJtYiZwP0TOrerLG3ZIupNc5D4C_T7H5jVU8fgvAM


### Create a post
POST http://localhost:4000/feed/post
Content-Type: application/json

{
  "title": "An",
  "content": "An awesome post content",
  "creator": "CREATOR ID"
}

### Find specific post
GET http://localhost:4000/feed/post/62ac546b895cca19ecaf98e4

### Update specific post
PUT http://localhost:4000/feed/post/62ac546b895cca19ecaf98e4
Content-Type: application/json

{
    "title": "An awesome post",
    "content": "An awesome post content",
    "creator": "CREATOR ID"
}

### Delete specific post
DELETE http://localhost:4000/feed/post/62ac546b895cca19ecaf98e4
