### Get all posts
GET http://localhost:4000/feed/posts


### Create a post
POST http://localhost:4000/feed/post
Content-Type: application/json

{
  "title": "An awesome post",
  "content": "An awesome post content",
  "creator": "CREATOR ID"
}

### Find specific post
GET http://localhost:4000/feed/post/62ac546b895cca19ecaf98e4

### Update specific post
PUT http://localhost:4000/feed/post/62ac546b895cca19ecaf98e4
Content-Type: application/json

{
    "title": "An awesome post",
    "content": "An awesome post content",
    "creator": "CREATOR ID"
}

### Delete specific post
DELETE http://localhost:4000/feed/post/62ac546b895cca19ecaf98e4
