### Get all posts
GET http://localhost:4000/feed/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJpbmFtcmFsYW1zYWxAZ21haWwuY29tIiwiX2lkIjoiNjJiODM5ZmY2YjBlYjZiZDU4OThiMmQyIiwiaWF0IjoxNjU2MjQwNjQwLCJleHAiOjE2NTg4MzI2NDB9.4mi6OWtnsDK8iEUhLv1kd1WHwdZ3cDRCSiwImS3ztB0


### Create a post
POST http://localhost:4000/feed/post
Content-Type: application/json

{
  "title": "An",
  "content": "An awesome post content"
}

### Find specific post
GET http://localhost:4000/feed/post/62ac546b895cca19ecaf98e4

### Update specific post
PUT http://localhost:4000/feed/post/62ac546b895cca19ecaf98e4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJpbmFtcmFsYW1zYWxAZ21haWwuY29tIiwiX2lkIjoiNjJiODM5ZmY2YjBlYjZiZDU4OThiMmQyIiwiaWF0IjoxNjU2MjQwNjQwLCJleHAiOjE2NTg4MzI2NDB9.4mi6OWtnsDK8iEUhLv1kd1WHwdZ3cDRCSiwImS3ztB0
Content-Type: application/json

{
    "title": "An awesome post",
    "content": "An awesome post content",
    "creator": "CREATOR ID"
}

### Delete specific post
DELETE http://localhost:4000/feed/post/62ac546b895cca19ecaf98e4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJpbmFtcmFsYW1zYWxAZ21haWwuY29tIiwiX2lkIjoiNjJiODM5ZmY2YjBlYjZiZDU4OThiMmQyIiwiaWF0IjoxNjU2MjQwNjQwLCJleHAiOjE2NTg4MzI2NDB9.4mi6OWtnsDK8iEUhLv1kd1WHwdZ3cDRCSiwImS3ztB0
